### ISSUE TITLE
Follow-ups for the Verifiable Builds - #1148

### ISSUE THREAD

**Issue by SkymanOne** [paritytech/cargo-contract#1214]
This is a tracking issue for all the follow-ups issues related to #1148  
```[tasklist]
### Tasks
- [x] A GH workflow for an automatic release of the image tag upon a new release of cargo-contract
- [ ] Specify the docker command to be used for the build
- [ ] Recognise relative path dependencies and `--manifest-path` path to mount respective directories to the container
- [ ] Optimise the docker resources by either reusing the same container or re-create a single container instance and mounting crates.io local index
```
