### ISSUE TITLE
Ensure building/checking depends on Wasm import functions being correct

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#163]
We want to examine the resulting contract Wasm in order to ensure that certain criteria are met.

# ToDo

- [ ] Ensure that building/checking happens only if the following conditions are fulfilled.
- [ ] Ensure that only `seal_*` functions are imported in the resulting contract Wasm.
- [ ] For functions which are not `seal_*` we want to give helpful messages:
    - [ ] Recommend `overflow-checks = false` when [this bug](https://github.com/rust-lang/rust/issues/78744) occurs.
    - [ ] If generated ink! constructs [like this](https://github.com/paritytech/ink/blob/master/crates/lang/codegen/src/generator/cross_calling.rs#L209) are found.
