### ISSUE TITLE
Make `cargo contract test` run the contract's doc tests as well

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#494]
Follow-up to https://github.com/paritytech/ink/pull/1198.

## Issue Description

`cargo test` does not run the doc tests for our contracts, because they're of type `cdylib` (relevant Rust issues: https://github.com/rust-lang/cargo/issues/4717, https://github.com/rust-lang/cargo/issues/2442).

## Ideas

Have `cargo contract test` temporarily remove `crate-type = ["cdylib"]` from the contract's `Cargo.toml`, run the doc tests, add it back afterwards.

What I dislike about this solution is that the contract is modified as a side-effect of a test, which is not idiomatic and might confuse the developer if the test e.g. panic's and leaves the contract in a dirty state.

The alternative would be to put the contract into a temp folder. In that case we would lose the cache though, everytime the tests are executed the `target` folder would be build anew.

## ToDo

- [] Make `cargo contract test` run the contract's doc tests as well.
- [] Add a flag `--doc` analog to `cargo test --doc`.
- [] Make all our CI's which test contracts use `cargo +nightly contract test` instead of executing `cargo test` on the contract.
