### ISSUE TITLE
Document need for even amount of digits for `--salt`

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#969]
This has confused people during workshops:

```
cargo contract instantiate --manifest-path=flipper/Cargo.toml --suri //Alice --skip-confirm --args true --salt 1 
error: invalid value '1' for '--salt <SALT>': Odd number of digits
```

We actually require an even amount of digits here.

## ToDo

- [ ] Check where this error of "Odd number of digits" comes from. 
- [ ] Should be something like `Odd number of digits founds, we require an even number of digits`.
- [ ] If this is always true for all Substrate chains, we should document if for the `cargo-contract` `--salt` param.
